const state={page:"dashboard",records:[]};
const data={
sales:[["SO-1048","Rajesh Patel","Residential • 5 kW","₹4,85,000","₹2,42,500","Approved"],["SO-1047","Shree Industries","Commercial • 25 kW","₹18,40,000","₹9,20,000","Installation"],["SO-1046","Mehta Residence","Residential • 3 kW","₹2,95,000","₹1,00,000","Quotation"]],
inventory:[["PANEL-550","Adani 550W Mono PERC","Solar Panel","124","40","84","₹9,92,000"],["INV-5K","Luminous 5kW Hybrid","Inverter","18","5","13","₹2,34,000"],["STR-01","GI Rooftop Structure","Structure","36","10","26","₹1,08,000"],["CABLE-DC","DC Solar Cable 6mm","Cable","820","200","620","₹1,24,000"],["MC4-PAIR","MC4 Connector Pair","Accessory","310","100","210","₹31,000"]],
customers:[["CUS-1001","Rajesh Patel","Residential","82001 23456","5 kW","₹2,42,500"],["CUS-1002","Shree Industries","Commercial","98765 43210","25 kW","₹9,20,000"],["CUS-1003","Mehta Residence","Residential","90909 11223","3 kW","₹1,95,000"],["CUS-1004","Kisan Agro","Industrial","98250 55667","40 kW","₹12,80,000"]],
suppliers:[["SUP-001","Waaree Energies","Solar Panels","24XXXXXXXXXX1Z5","Ahmedabad","₹4,85,000"],["SUP-002","Luminous Power","Inverters","24XXXXXXXXXX2Z4","Vadodara","₹2,15,000"],["SUP-003","Structure Works","Mounting Structures","Unregistered","Anand","₹1,36,000"]],
purchases:[["PO-208","Waaree Energies","Panels • 100 pcs","₹7,15,000","22 Sep 2026","Received"],["PO-207","Luminous","Inverters • 12 pcs","₹5,40,000","20 Sep 2026","Partial"],["PO-206","Local Structure Works","Structures • 25","₹2,10,000","18 Sep 2026","Received"]],
projects:[["DS-PRJ-026","Shree Industries","25 kW Commercial","Installation","72%","₹18.40 L"],["DS-PRJ-025","Rajesh Patel","5 kW Residential","Commissioning","92%","₹4.85 L"],["DS-PRJ-024","Kisan Agro","40 kW Industrial","Material Allocation","38%","₹27.60 L"],["DS-PRJ-023","Mehta Residence","3 kW Residential","Completed","100%","₹2.95 L"]]
};
const $=s=>document.querySelector(s);
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove("show"),2200)}
function badge(v){let c="badge-gray";if(/completed|received|approved|paid/i.test(v))c="badge-green";else if(/installation|partial|pending/i.test(v))c="badge-yellow";else if(/commission|quotation|draft/i.test(v))c="badge-blue";return '<span class="badge '+c+'">'+v+"</span>"}
function pageHead(title,sub,action=""){let label=title==="Inventory"?"Add Product":title==="Customers"?"Add Customer":title==="Sales"?"New Quotation":title==="Purchases"?"New Purchase":title==="Projects"?"New Project":title==="Service & Warranty"?"New Ticket":title==="Finance & Ledgers"?"Record Payment":title==="Suppliers"?"Add Supplier":"Create New";return '<div class="page-title"><div><h1>'+title+'</h1><p>'+sub+'</p></div>'+(action?'<button class="btn btn-primary" onclick="'+action+'">＋ '+label+'</button>':"")+'</div>'}
function table(headers,rows,clickable=true){return '<div class="card table-card"><div class="table-wrap"><table class="table"><thead><tr>'+headers.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+rows.map((r,ri)=>"<tr "+(clickable?'onclick="rowAction('+ri+')" style="cursor:pointer"':"")+">"+r.map((x,i)=>"<td>"+(i===0?"<strong>"+x+"</strong>":/₹/.test(x)?x:/^(Approved|Installation|Quotation|Received|Partial|Completed|Commissioning|Material Allocation|Pending|Paid|Advance received|Draft)$/.test(x)?badge(x):x)+"</td>").join("")+"</tr>").join("")+"</tbody></table></div></div>"}
function dashboard(){return pageHead("Good evening, Admin","Enterprise overview • FY 2026–27 • 23 September 2026")+
'<div class="grid stats">'+[["Net Sales","₹42,68,500","↑ 12.8% vs last month","▣"],["Receivables","₹18,42,750","12 invoices • ₹6.84 L overdue","₹"],["Inventory Value","₹31,84,200","5 SKUs below reorder level","▤"],["Active Projects","08","3 installations this week","◈"]].map(x=>'<div class="card stat"><div class="stat-top"><span>'+x[0]+'</span><span class="stat-icon">'+x[3]+'</span></div><h2>'+x[1]+'</h2><span class="trend">'+x[2]+'</span></div>').join("")+
'<div class="grid dashboard-grid"><div class="card"><div class="card-head"><h3>Revenue Performance</h3><span>Apr – Sep 2026</span></div><div class="card-body"><div class="chart">'+[42,55,48,71,65,88].map((v,i)=>'<div class="bar-wrap"><div class="bar" style="height:'+v+'%"></div><div class="bar-label">'+["Apr","May","Jun","Jul","Aug","Sep"][i]+"</div></div>").join("")+'</div><div class="legend">Invoiced sales • values shown for demonstration</div></div></div>'+
'<div class="card"><div class="card-head"><h3>Order-to-Cash Pipeline</h3><span>Current workload</span></div><div class="card-body pipeline">'+[["Quotation","4","₹8.2 L"],["Approved","3","₹21.4 L"],["Installation","2","₹12.6 L"],["Commissioning","1","₹4.8 L"]].map(x=>'<div><div class="pipeline-row"><span>'+x[0]+'</span><b>'+x[2]+'</b></div><div class="progress" style="margin-top:7px"><i style="width:'+parseInt(x[1])*20+'%"></i></div></div>').join("")+'</div></div></div>'+
'<div class="section-title">Control Centre</div><div class="grid mini-grid"><div class="card info"><small>STOCK CONTROL</small><strong>5 reorder alerts</strong><p><button class="btn btn-light" onclick="go(\'inventory\')">Open stock →</button></p></div><div class="card info"><small>CUSTOMER ACCOUNTING</small><strong>₹6.84 L overdue</strong><p><button class="btn btn-light" onclick="go(\'finance\')">Open receivables →</button></p></div><div class="card info"><small>SERVICE CONTROL</small><strong>4 warranty claims</strong><p><button class="btn btn-light" onclick="go(\'service\')">Open service →</button></p></div></div>'}
function listing(type,title,sub,headers,action){return pageHead(title,sub,action)+'<div class="toolbar"><input class="search" placeholder="⌕  Search '+title.toLowerCase()+'" oninput="filterRows(this)"><select class="filter" onchange="toast(this.value===\'All status\'?\'Showing all records\':\'Filter applied: \'+this.value)"><option>All status</option><option>Draft</option><option>Pending</option><option>Approved</option><option>Completed</option></select><button class="btn btn-light" onclick="toast(\'Excel export prepared (demo)\')">⇩ Export</button></div><div id="dataTable">'+table(headers,data[type])+'</div>'}
function projects(){return pageHead("Projects","End-to-end solar execution: survey → design → material → installation → commissioning","openModal('New Project')")+'<div class="grid mini-grid">'+data.projects.map(p=>'<div class="card project-card"><div class="project-meta"><span>'+p[0]+'</span>'+badge(p[3])+'</div><h3>'+p[1]+'</h3><p>'+p[2]+' • Project value '+p[5]+'</p><div class="project-meta"><span>Execution progress</span><b>'+p[4]+'</b></div><div class="progress"><i style="width:'+parseInt(p[4])+'%"></i></div><div class="kpi-row" style="margin-top:14px"><span class="kpi">Materials <b>Allocated</b></span><span class="kpi">Documents <b>12</b></span><span class="kpi">Margin <b>24.8%</b></span></div></div>').join("")}
function workflow(){return pageHead("Order Fulfilment","Linked document flow for a typical solar sale")+'<div class="card" style="padding:20px"><div class="kpi-row">'+["1. Quotation","2. Approval","3. Sales Order","4. Material Allocation","5. Installation","6. Invoice","7. Payment"].map((x,i)=>'<span class="kpi" style="flex:1;min-width:120px">STEP '+(i+1)+'<b>'+x.split(". ")[1]+'</b></span>').join("")+'</div><div class="section-title">Current Document Chain</div>'+table(["Document","Reference","Party","Value","Status"],[["Quotation","QT-1046","Mehta Residence","₹2,95,000","Quotation"],["Sales Order","SO-1046","Mehta Residence","₹2,95,000","Approved"],["Material Issue","MI-301","Warehouse → Site","₹1,86,000","Completed"],["Tax Invoice","INV-1046","Mehta Residence","₹2,95,000","Pending"],["Receipt","REC-1090","Mehta Residence","₹1,00,000","Paid"]],false)+'</div>'}
function service(){return pageHead("Service & Warranty","Tickets, preventive maintenance, warranty claims and field visits","openModal('New Service Ticket')")+'<div class="grid stats">'+[["Open Tickets","07","2 high priority"],["Warranty Claims","04","1 awaiting approval"],["Visits This Week","13","3 completed today"],["Avg. Resolution","1.8d","Within service target"]].map(x=>'<div class="card stat"><div class="stat-top"><span>'+x[0]+'</span></div><h2>'+x[1]+'</h2><span class="trend">'+x[2]+'</span></div>').join("")+'</div>'+table(["Ticket","Customer","Issue","Technician","Priority","Status"],[["SR-5021","Rajesh Patel","Inverter error E07","Amit","High","Pending"],["SR-5020","Kisan Agro","Panel performance check","Rakesh","Normal","Installation"],["SR-5019","Shree Industries","ACDB inspection","Jay","Normal","Completed"],["WR-104","Mehta Residence","Panel replacement","Amit","High","Pending"]])}
function finance(){return pageHead("Finance & Ledgers","Receivables, payables, payments, expenses and document settlement","openModal('Record Payment')")+'<div class="grid stats">'+[["Receivables","₹18.43 L","12 invoices"],["Payables","₹9.72 L","7 suppliers"],["Expenses • Sep","₹4.86 L","↓ 4.2%"],["Gross Margin","28.6%","Before tax"]].map(x=>'<div class="card stat"><div class="stat-top"><span>'+x[0]+'</span></div><h2>'+x[1]+'</h2><span class="trend">'+x[2]+'</span></div>').join("")+'</div>'+table(["Date","Reference","Party","Type","Amount","Method","Status"],[["23 Sep 2026","REC-1092","Rajesh Patel","Customer Receipt","₹1,00,000","UPI","Paid"],["22 Sep 2026","PAY-771","Waaree Energies","Supplier Payment","₹3,50,000","Bank","Paid"],["21 Sep 2026","EXP-442","Transport Vendor","Expense","₹18,600","UPI","Paid"],["20 Sep 2026","REC-1091","Shree Industries","Customer Receipt","₹4,00,000","Bank","Pending"]])}
function reports(){return pageHead("Reports & Analytics","Operational, financial, inventory, GST-ready and project intelligence")+'<div class="grid mini-grid">'+["Sales & Revenue","Purchase & Vendor","Stock & Valuation","GST Summary","Receivable Aging","Project Profitability","Expense Analysis","Service Performance","Warranty Register"].map((x,i)=>'<div class="card info"><small>REPORT '+String(i+1).padStart(2,"0")+'</small><strong>'+x+'</strong><p><button class="btn btn-light" onclick="toast(\'Report preview opened — demo data\')">View report →</button></p></div>').join("")+'</div>'}
function settings(){return pageHead("Settings","Company, GST, tax masters, numbering, warehouses, users, roles and integrations")+'<div class="card settings"><div class="settings-nav">'+["Company Profile","GST & Tax","Invoice Settings","Warehouses","Users & Roles","HSN / SAC","Payment Methods","Notifications","Integrations","Backup & Security"].map((x,i)=>'<button class="'+(i===0?"active":"")+'" onclick="toast(\''+x+' settings selected\')">'+x+'</button>').join("")+'</div><div class="settings-body"><h3 style="margin-top:0">Company Profile</h3><div class="grid mini-grid"><div class="info"><small>LEGAL / TRADE NAME</small><strong>Destiny Solar</strong></div><div class="info"><small>GSTIN</small><strong>24XXXXXXXXXX1Z5</strong></div><div class="info"><small>BUSINESS TYPE</small><strong>Proprietorship</strong></div><div class="info"><small>STATE / CODE</small><strong>Gujarat • 24</strong></div><div class="info"><small>FINANCIAL YEAR</small><strong>2026–27</strong></div><div class="info"><small>INVOICE SERIES</small><strong>DS/26-27/</strong></div></div><div class="section-title">Governance Controls</div><label class="check"><input type="checkbox" checked> Approval required before Sales Order confirmation</label><label class="check"><input type="checkbox" checked> Serial tracking for panels and inverters</label><label class="check"><input type="checkbox" checked> Audit trail for financial transactions</label><label class="check"><input type="checkbox" checked> Prevent stock issue when available quantity is insufficient</label></div></div>'}
function openModal(title){$("#modalTitle").textContent=title;const isSale=/Quotation|Purchase|Product|Customer|Supplier|Project|Ticket|Payment/.test(title);$("#modalBody").innerHTML='<div class="form"><div class="field"><label>Document / Party</label><input placeholder="Enter name or reference"></div><div class="field"><label>GSTIN / Phone</label><input placeholder="Enter details"></div><div class="field full"><label>Item / Description</label><input placeholder="Search product, service or description"></div><div class="field"><label>Quantity / Amount</label><input placeholder="0"></div><div class="field"><label>Tax / Status</label><select><option>Draft</option><option>Pending Approval</option><option>Approved</option></select></div><div class="field"><label>Warehouse / Site</label><select><option>Main Warehouse</option><option>Project Site</option><option>Service Vehicle</option></select></div><div class="field"><label>Payment Terms</label><select><option>Advance</option><option>15 Days</option><option>30 Days</option></select></div><div class="field full"><label>Notes / Remarks</label><textarea placeholder="Enter notes"></textarea></div><div class="form-actions"><button class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveModal()">Save & Continue</button></div></div>' ;$("#modal").classList.add("show")}
function closeModal(){$("#modal").classList.remove("show")}
function saveModal(){closeModal();toast("Transaction saved • next workflow step available in production")}
function filterRows(el){const q=el.value.toLowerCase();document.querySelectorAll("#dataTable tbody tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?"":"none")}
function rowAction(i){const p=state.page;const title=p==="sales"?"Sales Order":p==="inventory"?"Inventory Item":p==="customers"?"Customer Master":p==="suppliers"?"Supplier Master":p==="purchases"?"Purchase Order":"Record";openModal("View "+title)}
function go(p){state.page=p;render();document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===p));window.scrollTo({top:0,behavior:"smooth"})}
function render(){const p=state.page;$("#crumb").textContent=p==="dashboard"?"Dashboard":p==="workflow"?"Order Fulfilment":p.replace(/(^| )\S/g,x=>x.toUpperCase());let html;if(p==="dashboard")html=dashboard();else if(p==="sales")html=listing("sales","Sales","Quotations → Sales Orders → Delivery → Invoice → Collection",["Document","Customer","System","Order Value","Received","Status"],"openModal('New Quotation')");else if(p==="inventory")html=listing("inventory","Inventory","Multi-warehouse stock, serials, batches, allocation and reorder control",["SKU","Product","Category","On Hand","Reserved","Available","Stock Value"],"openModal('Add Product')");else if(p==="customers")html=listing("customers","Customers","Customer master, GST profile, projects, documents and receivables",["ID","Customer","Segment","Phone","System","Outstanding"],"openModal('Add Customer')");else if(p==="suppliers")html=listing("suppliers","Suppliers","Vendor master, GST profile, purchase history and payables",["ID","Supplier","Category","GSTIN","Location","Outstanding"],"openModal('Add Supplier')");else if(p==="purchases")html=listing("purchases","Purchases","RFQ → Purchase Order → GRN → Supplier Invoice → Payment",["PO","Supplier","Items","Value","Delivery","Status"],"openModal('New Purchase')");else if(p==="projects")html=projects();else if(p==="workflow")html=workflow();else if(p==="service")html=service();else if(p==="finance")html=finance();else if(p==="reports")html=reports();else html=settings();$("#content").innerHTML=html}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{go(b.dataset.page);$("#sidebar").classList.remove("open")}));
$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
$("#searchBtn").onclick=()=>{openModal("Global Search");toast("Search across customers, documents, serials and projects")};
$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
render();