const state={page:"dashboard"};
const data={
sales:[
["SO-1048","Rajesh Patel","Residential • 5 kW","₹4,85,000","Advance received","Approved"],
["SO-1047","Shree Industries","Commercial • 25 kW","₹18,40,000","₹9,20,000","Installation"],
["SO-1046","Mehta Residence","Residential • 3 kW","₹2,95,000","₹1,00,000","Quotation"] ],
inventory:[
["PANEL-550","Adani 550W Mono PERC","Solar Panel","124","40","84","₹9,920"],
["INV-5K","Luminous 5kW Hybrid","Inverter","18","5","13","₹2,34,000"],
["STR-01","GI Rooftop Structure","Structure","36","10","26","₹1,08,000"],
["CABLE-DC","DC Solar Cable 6mm","Cable","820","200","620","₹1,24,000"],
["MC4-PAIR","MC4 Connector Pair","Accessory","310","100","210","₹31,000"]],
customers:[
["CUS-1001","Rajesh Patel","Residential","82001 23456","5 kW","₹2,42,500"],
["CUS-1002","Shree Industries","Commercial","98765 43210","25 kW","₹9,20,000"],
["CUS-1003","Mehta Residence","Residential","90909 11223","3 kW","₹1,95,000"],
["CUS-1004","Kisan Agro","Industrial","98250 55667","40 kW","₹12,80,000"]],
purchases:[
["PO-208","Waaree Energies","Panels • 100 pcs","₹7,15,000","22 Sep 2026","Received"],
["PO-207","Luminous","Inverters • 12 pcs","₹5,40,000","20 Sep 2026","Partial"],
["PO-206","Local Structure Works","Structures • 25","₹2,10,000","18 Sep 2026","Received"]],
projects:[
["DS-PRJ-026","Shree Industries","25 kW Commercial","Installation","72%","₹18.40 L"],
["DS-PRJ-025","Rajesh Patel","5 kW Residential","Commissioning","92%","₹4.85 L"],
["DS-PRJ-024","Kisan Agro","40 kW Industrial","Material Allocation","38%","₹27.60 L"],
["DS-PRJ-023","Mehta Residence","3 kW Residential","Completed","100%","₹2.95 L"]]
};
const $=s=>document.querySelector(s);
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function badge(v){let c="badge-gray";if(/completed|received|approved|paid/i.test(v))c="badge-green";else if(/installation|partial|pending/i.test(v))c="badge-yellow";else if(/commission|quotation/i.test(v))c="badge-blue";return '<span class="badge '+c+'">'+v+"</span>"}
function pageHead(title,sub,action=""){return '<div class="page-title"><div><h1>'+title+'</h1><p>'+sub+'</p></div>'+(action?'<button class="btn btn-primary" onclick="'+action+'">＋ '+(title==="Inventory"?"Add Product":title==="Customers"?"Add Customer":title==="Sales"?"New Quotation":title==="Purchases"?"New Purchase":"Create New")+'</button>':"")+'</div>'}
function table(headers,rows){return '<div class="card table-card"><div class="table-wrap"><table class="table"><thead><tr>'+headers.map(x=>"<th>"+x+"</th>").join("")+"</tr></thead><tbody>"+rows.map(r=>"<tr>"+r.map((x,i)=>"<td>"+(i===0?"<strong>"+x+"</strong>":/₹/.test(x)?x:/^(Approved|Installation|Quotation|Received|Partial|Completed|Commissioning|Material Allocation|Pending|Paid|Advance received)$/.test(x)?badge(x):x)+"</td>").join("")+"</tr>").join("")+"</tbody></table></div></div>"}
function dashboard(){
return pageHead("Good evening, Admin","Business overview • 23 September 2026")+
'<div class="grid stats">'+[
["Total Sales","₹42,68,500","↑ 12.8% this month","▣"],["Receivables","₹18,42,750","12 invoices overdue","₹"],["Stock Value","₹31,84,200","5 items low stock","▤"],["Active Projects","08","3 installations this week","◈"]].map(x=>'<div class="card stat"><div class="stat-top"><span>'+x[0]+'</span><span class="stat-icon">'+x[3]+'</span></div><h2>'+x[1]+'</h2><span class="trend">'+x[2]+'</span></div>').join("")+
'<div class="grid dashboard-grid"><div class="card"><div class="card-head"><h3>Sales Overview</h3><span>Apr – Sep 2026</span></div><div class="card-body"><div class="chart">'+[42,55,48,71,65,88].map((v,i)=>'<div class="bar-wrap"><div class="bar" style="height:'+v+'%"></div><div class="bar-label">'+["Apr","May","Jun","Jul","Aug","Sep"][i]+"</div></div>").join("")+'</div><div class="legend">Monthly invoiced sales</div></div></div>'+
'<div class="card"><div class="card-head"><h3>Project Pipeline</h3><span>8 active</span></div><div class="card-body pipeline">'+[["Quotation","4","₹8.2 L","badge-blue"],["Approved","3","₹21.4 L","badge-green"],["Installation","2","₹12.6 L","badge-yellow"],["Commissioning","1","₹4.8 L","badge-blue"]].map(x=>'<div><div class="pipeline-row"><span>'+x[0]+'</span><b>'+x[2]+'</b></div><div class="progress" style="margin-top:7px"><i style="width:'+x[1]*20+'%"></i></div></div>').join("")+'</div></div></div>'+
'<div class="section-title">Attention Required</div><div class="grid mini-grid"><div class="card info"><small>Low Stock</small><strong>5 items need reorder</strong><p><button class="btn btn-light" onclick="go(\'inventory\')">Review inventory</button></p></div><div class="card info"><small>Receivables</small><strong>₹6.84 L overdue</strong><p><button class="btn btn-light" onclick="go(\'finance\')">View ledger</button></p></div><div class="card info"><small>Warranty</small><strong>4 claims pending</strong><p><button class="btn btn-light" onclick="go(\'service\')">Open service</button></p></div></div>';
}
function listing(type,title,sub,headers,action){let rows=data[type];return pageHead(title,sub,action)+'<div class="toolbar"><input class="search" placeholder="⌕  Search '+title.toLowerCase()+'" oninput="filterRows(this)"><select class="filter"><option>All status</option><option>Active</option><option>Pending</option><option>Completed</option></select><button class="btn btn-light" onclick="toast(\'Export prepared for Excel\')">⇩ Export</button></div><div id="dataTable">'+table(headers,rows)+'</div>'}
function projects(){return pageHead("Projects","Track solar projects from survey to commissioning","openModal(\'New Project\')")+'<div class="grid mini-grid">'+data.projects.map(p=>'<div class="card project-card"><div class="project-meta"><span>'+p[0]+'</span>'+badge(p[3])+'</div><h3>'+p[1]+'</h3><p>'+p[2]+' • Project value '+p[5]+'</p><div class="project-meta"><span>Progress</span><b>'+p[4]+'</b></div><div class="progress"><i style="width:'+parseInt(p[4])+'%"></i></div><div class="kpi-row" style="margin-top:14px"><span class="kpi">Materials <b>Allocated</b></span><span class="kpi">Documents <b>12</b></span></div></div>').join("")+'</div>'}
function service(){return pageHead("Service & Warranty","Tickets, preventive maintenance and warranty claims","openModal(\'New Service Ticket\')")+'<div class="grid stats"><div class="card stat"><div class="stat-top"><span>Open Tickets</span></div><h2>07</h2><span class="trend">2 high priority</span></div><div class="card stat"><div class="stat-top"><span>Warranty Claims</span></div><h2>04</h2><span class="trend">1 awaiting approval</span></div><div class="card stat"><div class="stat-top"><span>Visits This Week</span></div><h2>13</h2><span class="trend">↑ 3 from last week</span></div><div class="card stat"><div class="stat-top"><span>Avg. Resolution</span></div><h2>1.8d</h2><span class="trend">Within target</span></div></div>'+table(["Ticket","Customer","Issue","Technician","Priority","Status"],[["SR-5021","Rajesh Patel","Inverter error E07","Amit","High","Pending"],["SR-5020","Kisan Agro","Panel performance check","Rakesh","Normal","Installation"],["SR-5019","Shree Industries","ACDB inspection","Jay","Normal","Completed"],["WR-104","Mehta Residence","Panel replacement","Amit","High","Pending"]])}
function finance(){return pageHead("Finance & Ledgers","Receivables, payables, payments and expenses","openModal(\'Record Payment\')")+'<div class="grid stats"><div class="card stat"><div class="stat-top"><span>Receivables</span></div><h2>₹18.43 L</h2><span class="trend">12 invoices</span></div><div class="card stat"><div class="stat-top"><span>Payables</span></div><h2>₹9.72 L</h2><span class="trend">7 suppliers</span></div><div class="card stat"><div class="stat-top"><span>This Month Expenses</span></div><h2>₹4.86 L</h2><span class="trend">↓ 4.2%</span></div><div class="card stat"><div class="stat-top"><span>Gross Margin</span></div><h2>28.6%</h2><span class="trend">Before tax</span></div></div>'+table(["Date","Reference","Party","Type","Amount","Method","Status"],[["23 Sep 2026","REC-1092","Rajesh Patel","Customer Receipt","₹1,00,000","UPI","Paid"],["22 Sep 2026","PAY-771","Waaree Energies","Supplier Payment","₹3,50,000","Bank","Paid"],["21 Sep 2026","EXP-442","Transport Vendor","Expense","₹18,600","UPI","Paid"],["20 Sep 2026","REC-1091","Shree Industries","Customer Receipt","₹4,00,000","Bank","Pending"]])}
function reports(){return pageHead("Reports & Analytics","Business intelligence, GST-ready summaries and operational reports")+'<div class="grid mini-grid">'+["Sales & Revenue","Purchase & Vendor","Stock & Valuation","GST Summary","Receivable Aging","Project Profitability","Expense Analysis","Service Performance","Warranty Register"].map((x,i)=>'<div class="card info"><small>REPORT '+String(i+1).padStart(2,"0")+'</small><strong>'+x+'</strong><p><button class="btn btn-light" onclick="toast(\'Report preview opened\')">View report →</button></p></div>').join("")+'</div>'}
function settings(){return pageHead("Settings","Configure company, GST, numbering, users and integrations")+'<div class="card settings"><div class="settings-nav">'+["Company Profile","GST & Tax","Invoice Settings","Warehouses","Users & Roles","HSN / SAC","Payment Methods","Notifications","Integrations","Backup & Security"].map((x,i)=>'<button class="'+(i===0?"active":"")+'" onclick="toast(\''+x+' settings selected\')">'+x+'</button>').join("")+'</div><div class="settings-body"><h3 style="margin-top:0;font-size:15px">Company Profile</h3><div class="grid mini-grid"><div class="info"><small>LEGAL / TRADE NAME</small><strong>Destiny Solar</strong></div><div class="info"><small>GSTIN</small><strong>24XXXXXXXXXX1Z5</strong></div><div class="info"><small>BUSINESS TYPE</small><strong>Proprietorship</strong></div><div class="info"><small>STATE</small><strong>Gujarat • 24</strong></div><div class="info"><small>FINANCIAL YEAR</small><strong>2026–27</strong></div><div class="info"><small>INVOICE PREFIX</small><strong>DS/26-27/</strong></div></div><div class="section-title">Operational Controls</div><label class="check"><input type="checkbox" checked> Require approval before converting quotation to sales order</label><label class="check"><input type="checkbox" checked> Track serial numbers for panels and inverters</label><label class="check"><input type="checkbox" checked> Maintain audit trail for financial transactions</label></div></div>'}
function openModal(title){$("#modalTitle").textContent=title;$("#modalBody").innerHTML='<div class="form"><div class="field"><label>Name / Party</label><input placeholder="Enter name"></div><div class="field"><label>Phone / Reference</label><input placeholder="Enter details"></div><div class="field full"><label>Item / Description</label><input placeholder="Enter item or description"></div><div class="field"><label>Amount / Quantity</label><input placeholder="0"></div><div class="field"><label>Status</label><select><option>Draft</option><option>Pending</option><option>Approved</option></select></div><div class="field full"><label>Notes</label><textarea placeholder="Additional notes"></textarea></div><div class="form-actions"><button class="btn btn-light" onclick="closeModal()">Cancel</button><button class="btn btn-primary" onclick="saveModal()">Save Record</button></div></div>';$("#modal").classList.add("show")}
function closeModal(){$("#modal").classList.remove("show")}
function saveModal(){closeModal();toast("Record saved successfully (demo)")}
function filterRows(el){const q=el.value.toLowerCase();document.querySelectorAll("#dataTable tbody tr").forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?"":"none")}
function go(p){state.page=p;render();document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===p))}
function render(){const p=state.page;$("#crumb").textContent=p==="dashboard"?"Dashboard":p.replace(/(^| )\S/g,x=>x.toUpperCase());let html;if(p==="dashboard")html=dashboard();else if(p==="sales")html=listing("sales","Sales","Quotations, orders, invoices and customer collections",["Number","Customer","System","Value","Payment","Status"],"openModal('New Quotation')");else if(p==="inventory")html=listing("inventory","Inventory","Multi-warehouse stock, serials, batches and reorder control",["SKU","Product","Category","On Hand","Reserved","Available","Stock Value"],"openModal('Add Product')");else if(p==="customers")html=listing("customers","Customers","CRM, project history, GST details and receivables",["ID","Customer","Type","Phone","System","Outstanding"],"openModal('Add Customer')");else if(p==="purchases")html=listing("purchases","Purchases","Supplier quotations, purchase orders, GRN and bills",["PO","Supplier","Items","Value","Delivery","Status"],"openModal('New Purchase')");else if(p==="projects")html=projects();else if(p==="service")html=service();else if(p==="finance")html=finance();else if(p==="reports")html=reports();else html=settings();$("#content").innerHTML=html}
document.querySelectorAll(".nav-item").forEach(b=>b.addEventListener("click",()=>{go(b.dataset.page);$("#sidebar").classList.remove("open")}));
$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
$("#searchBtn").onclick=()=>toast("Global search: customers, invoices, serials, projects…");
$("#modal").onclick=e=>{if(e.target.id==="modal")closeModal()};
render();